name: 'Sign Temperature'

on:
  push:
    branches:
      - main

jobs:
  temp_sign:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7.4', '3.8', '3.9']
    steps:
      - name: 'checkout codes'
        uses: actions/checkout@v3
      - name: 'set python'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: 'install dependencies'
        run: python -m pip install --upgrade onnxruntime
      - name: 'start'

        run: python index.py