name: 'Sign Temperature'

on:
  push:
    branches:
      - main

jobs:
  temp_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout codes'
        uses: actions/checkout@v2
      - name: 'set python'
        uses: actions/setup-python@v1
      - name: 'install dependencies'
        run: python -m pip install --upgrade dddd_ocr
      - name: 'start'

        run: python index.py